### ISSUE TITLE
XSS vulnerability in data-i18nfilter

### ISSUE THREAD

**Issue by cnsgithub** [masbaehr/nicecountryinput#4]
**Environment**
niceCountryInput version 1.0.2

**How to reproduce?**
This will show up an alert box:
```html
        <div class="niceCountryInputSelector" style="width: 300px;" data-selectedcountry="US" data-showspecial="false" data-showflags="true" data-i18nall="All selected"
            data-i18nnofilter="No selection" data-i18nfilter="Filter'/&gt;&lt;script&gt;alert('xss');&lt;/script&gt;&lt;div id='" data-onchangecallback="onChangeCallback" />
        </div>
```

**Expected result**
Proper HTML escaping

**Comment by cnsgithub** [comment]
The attributes `data-i18nall`, `data-i18nnofilter` and `data-i18nwait` (https://github.com/masbaehr/nicecountryinput/pull/3) are also affected.

Mitigation could be possible by introducing and making use of:
```javascript
NiceCountryInput.prototype.escapeHTML = function(value) {
    return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}
```

**Comment by masbaehr** [comment]
Used the mustache.js solution referenced here, since it had most upvote:
https://stackoverflow.com/questions/24816/escaping-html-strings-with-jquery
Thanks! As usual Mr.security ;)
